// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyedbsaxhebpttkeortm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZWRic2F4aGVicHR0a2VvcnRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MDgzMjksImV4cCI6MjA1MDI4NDMyOX0.c58pwmhKo9ncP0PxqJ7mrQyNUqV-jL4d6HuUHCdePr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);